# Generated by Django 5.2.6 on 2025-12-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmission',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
