# Generated by Django 5.2.6 on 2025-12-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_addmission_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmission',
            old_name='photo',
            new_name='image',
        ),
    ]
