# Generated by Django 5.2.6 on 2025-12-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_rename_photo_addmission_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmission',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
