# Generated by Django 5.2.6 on 2025-12-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_addmission_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmission',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
